### import numpy

In [1]:
import numpy as np

In [3]:
# create an array with a specified data type
arr = np.array([1,2,3])
print(arr)

[1 2 3]


# Create Arrays

### create an array from a Python array

In [ ]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


### create an array in a specified data type

In [ ]:
arr = np.array([[1,2,3], [4,5,6]], dtype='i2')
#i2 is integer

print(arr)

[[1 2 3]
 [4 5 6]]


### create an aray of evenly spaced values within a specified interval

In [ ]:
# np.arange(start, stop, step)
arr = np.arange(0, 20, 2)  
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


### create an array of evenly spaced numbers in a specified interval

In [ ]:
# np.linspace(start, stop, num_of_elements, endpoint=True, retstep=False) 
arr = np.linspace(0, 10, 20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


### create an array of random values in a given shape

In [ ]:
arr = np.random.rand(3, 3)
print(arr)

[[0.01193679 0.24119962 0.45164836]
 [0.59037498 0.56362195 0.8405065 ]
 [0.82843098 0.25080516 0.14234631]]


### create an array of zeros in a given shape 

In [4]:
zeros = np.zeros((2,3), dtype='i2')
print(zeros)

[[0 0 0]
 [0 0 0]]


### create an array of zeros with the same shape and data type as a given array

In [ ]:
zeros = np.zeros_like(arr)
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### create an array of ones in a given shape 

In [ ]:
ones = np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


### create an array of ones with the same shape and data type as a given array

In [ ]:
ones = np.ones_like(arr)
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### create an array of arbitrary values in a given shape 

In [ ]:
empty = np.empty((2,3))
print(empty)

[[1. 1. 1.]
 [1. 1. 1.]]


### create an array of constant values in a given shape  

In [ ]:
p = np.full((2,3), 5)
print(p)

[[5 5 5]
 [5 5 5]]


### create an array of constant values with the same shape and data type as a given array

In [ ]:
p = np.full_like(arr, 5)
print(p)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


### create an array by repetition

In [ ]:
# repeat each element of an array by a specified number of times
# np.repeat(iterable, reps, axis=None)
arr = [0, 1, 2]
print(np.repeat(arr, 3))   

[0 0 0 1 1 1 2 2 2]


In [ ]:
# repeat an array by a specified number of times
arr = [0, 1, 2]
print(np.tile(arr, 3))

[0 1 2 0 1 2 0 1 2]


### create an identity matrix with a given diagonal size

In [ ]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### create an identity matrix with a diagonal offset

In [ ]:
identity_matrix = np.eye(5, k=1)    # positive number shifts the diagonal upward
print(identity_matrix)

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


In [ ]:
identity_matrix = np.eye(5, k=-2)   # negative number shifts the diagonal downward
print(identity_matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


### extract the diagonal array / create a diagonal array

In [ ]:
arr = np.random.rand(5,5)
print(arr)

[[0.07710888 0.68905534 0.81142113 0.60805738 0.14322708]
 [0.70950747 0.11738625 0.5630424  0.27911771 0.91741603]
 [0.62715481 0.8857803  0.22214541 0.56813747 0.97598708]
 [0.65309756 0.78466617 0.40848438 0.01693925 0.18625553]
 [0.97973236 0.15756793 0.28687775 0.1440273  0.08333093]]


In [ ]:
# extract the diagonal
print(np.diag(arr))

[0.07710888 0.11738625 0.22214541 0.01693925 0.08333093]


In [ ]:
# create a matrix with a specified diagonal array
arr = np.diag([1,2,3,4,5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


# Inspect Arrays

In [ ]:
print(arr.shape)

(2, 3)


### inspect length of an array

In [ ]:
print(len(arr))

2


### inspect the number of dimensions of an array

In [ ]:
print(arr.ndim)

2


### inspect the number of elements in an array

In [ ]:
print(arr.size)

6


# Math Functions

In [ ]:
arr = np.random.rand(5,5)

### element-wise addition, subtraction, multiplication and division

In [ ]:
print(arr + 10)
print(arr - 10)
print(arr * 10)
print(arr / 10)

[[10.87350227 10.02942373 10.55204372 10.2402475  10.88480501]
 [10.46023842 10.19317033 10.2936925  10.81792751 10.55948738]
 [10.67792545 10.80912668 10.86857215 10.41799246 10.05893816]
 [10.478459   10.52115943 10.58063202 10.309199   10.91988263]
 [10.6553475  10.34924138 10.54109404 10.4490534  10.28232096]]
[[-9.12649773 -9.97057627 -9.44795628 -9.7597525  -9.11519499]
 [-9.53976158 -9.80682967 -9.7063075  -9.18207249 -9.44051262]
 [-9.32207455 -9.19087332 -9.13142785 -9.58200754 -9.94106184]
 [-9.521541   -9.47884057 -9.41936798 -9.690801   -9.08011737]
 [-9.3446525  -9.65075862 -9.45890596 -9.5509466  -9.71767904]]
[[8.73502266 0.29423734 5.52043722 2.40247504 8.84805011]
 [4.60238424 1.9317033  2.93692504 8.17927508 5.59487376]
 [6.77925447 8.09126678 8.68572154 4.17992456 0.58938156]
 [4.78459005 5.2115943  5.8063202  3.09198998 9.19882625]
 [6.55347503 3.49241385 5.41094045 4.49053396 2.82320961]]
[[0.08735023 0.00294237 0.05520437 0.02402475 0.0884805 ]
 [0.04602384 0.0193

In [ ]:
arr1 = np.array([1,2,3])
# the above operations can be performed using numpy built-in functions
# which can save memory as the output can be stored in the original array rather than assigning new memoryarr = np.array([1,2,3])
np.add(arr1, [8,9,10], out=arr1)
print(arr1)

np.subtract(arr1, [8,9,10], out=arr1)
print(arr1)

np.multiply(arr1, [1,2,3], out=arr1)
print(arr1)

[ 9 11 13]
[1 2 3]
[1 4 9]


### element-wise exponentiation

In [ ]:
print(np.exp(arr))

[[2.39528511 1.02986089 1.73679893 1.27156383 2.42251198]
 [1.58445171 1.2130894  1.34137137 2.26579912 1.74977529]
 [1.96978706 2.2459457  2.38350515 1.51890922 1.06070964]
 [1.61358596 1.68397897 1.7871676  1.36233345 2.50899588]
 [1.92581163 1.41799143 1.71788528 1.56682832 1.32620431]]


### element-wise logorithm

In [ ]:
# natural log
print(np.log(arr))      

[[-0.13524456 -3.52595367 -0.59412803 -1.42608562 -0.12238798]
 [-0.77601061 -1.64418294 -1.22522197 -0.20098157 -0.58073432]
 [-0.38871796 -0.21179979 -0.14090462 -0.87229189 -2.83126659]
 [-0.73718475 -0.65169928 -0.54363808 -1.1737702  -0.0835092 ]
 [-0.42258965 -1.05199195 -0.61416218 -0.80061348 -1.2647107 ]]


In [ ]:
# base 2
print(np.log2(arr))     

[[-0.19511665 -5.08687587 -0.85714556 -2.05740665 -0.17656854]
 [-1.11954666 -2.37205457 -1.76762165 -0.28995511 -0.83782252]
 [-0.56080147 -0.3055625  -0.20328239 -1.25845119 -4.08465428]
 [-1.06353278 -0.94020332 -0.78430396 -1.69339245 -0.12047831]
 [-0.60966799 -1.51770357 -0.88604873 -1.15504109 -1.82459185]]


In [ ]:
# base 10
print(np.log10(arr))    

[[-0.05873596 -1.53130222 -0.25802652 -0.61934112 -0.05315243]
 [-0.33701713 -0.71405958 -0.53210714 -0.08728519 -0.25220971]
 [-0.16881806 -0.09198348 -0.0611941  -0.37883156 -1.22960346]
 [-0.32015527 -0.2830294  -0.23609902 -0.50976192 -0.03626758]
 [-0.18352835 -0.4568743  -0.26672725 -0.34770202 -0.54925688]]


### element-wise square root

In [ ]:
print(np.sqrt(arr))

[[0.93461343 0.17153348 0.74299645 0.49015049 0.94064075]
 [0.67840874 0.43951147 0.54193404 0.90439345 0.74798889]
 [0.82336228 0.89951469 0.93197219 0.64652336 0.24277182]
 [0.69170731 0.72191373 0.76199214 0.55605665 0.95910512]
 [0.80953536 0.59096648 0.73559095 0.67011446 0.53133884]]


### element-wise sine and cosine

In [ ]:
print(np.sin(arr))

[[0.7665826  0.02941949 0.52442846 0.23794303 0.77379149]
 [0.44416174 0.19197122 0.28948859 0.72973036 0.5307518 ]
 [0.62717856 0.72368474 0.76340745 0.40592657 0.05890404]
 [0.46041177 0.49788598 0.54855249 0.30429572 0.79553051]
 [0.60943479 0.34218509 0.51507406 0.43411297 0.27858547]]


In [ ]:
print(np.cos(arr))

[[0.64214571 0.99956715 0.85145452 0.97127911 0.63344039]
 [0.89594662 0.98140056 0.95718147 0.68373503 0.8475273 ]
 [0.77887551 0.69013071 0.64591723 0.9139057  0.99826365]
 [0.88770547 0.8672425  0.83611612 0.95257762 0.60591354]
 [0.7928362  0.93963257 0.85714568 0.90085844 0.96041144]]


### sum along a specified axis

In [ ]:
# sum along the row
print(np.sum(arr, axis=0))    

[3.14547265 1.90212156 2.83603444 2.23441986 2.70543413]


In [ ]:
# sum along the column
print(np.sum(arr, axis=1))    

[2.58002224 2.32451614 2.83255489 2.80933208 2.27705729]


### compute the min and max along a specified axis

In [ ]:
# calculate min along the row
print(np.min(arr, axis=0))

[0.46023842 0.02942373 0.2936925  0.2402475  0.05893816]


In [ ]:
# calculate max along the column
print(np.max(arr, axis=1))    

[0.88480501 0.81792751 0.86857215 0.91988263 0.6553475 ]


### compute element-wise min and max of two arrays

In [ ]:
arr1 = np.array([1, 3, 5, 7, 9])
arr2 = np.array([0, 4, 3, 8, 7])
print(np.maximum(arr1, arr2))
print(np.minimum(arr1, arr2))

[1 4 5 8 9]
[0 3 3 7 7]


### compute the mean

In [ ]:
# compute the overall mean
print(np.mean(arr))

0.5129393054604379


In [ ]:
# compute the mean along the row
print(np.mean(arr, axis=0))   

[0.62909453 0.38042431 0.56720689 0.44688397 0.54108683]


In [ ]:
# compute the mean along the column
print(np.mean(arr, axis=1)) 

[0.51600445 0.46490323 0.56651098 0.56186642 0.45541146]


### compute the median

In [ ]:
# compute the overall median
print(np.median(arr))

0.52115942968839


In [ ]:
# compute the median along the row
print(np.median(arr, axis=0)) 

[0.6553475  0.34924138 0.55204372 0.41799246 0.55948738]


In [ ]:
# compute the median along the column
print(np.median(arr, axis=1))

[0.55204372 0.46023842 0.67792545 0.52115943 0.4490534 ]


### compute the standard deviation & variance

In [ ]:
# compute the overall standard deviation
print(np.std(arr))

0.25305273176784365


In [ ]:
# compute the standard deviation along the row
print(np.std(arr, axis=0))

[0.15100481 0.26938074 0.18260514 0.20008424 0.33508033]


In [ ]:
# compute the standard deviation along the column
print(np.std(arr, axis=1))

[0.33997649 0.21759869 0.29739013 0.20049061 0.13310804]


In [ ]:
# compute the overall variance
print(np.var(arr))

0.06403568505516823


In [ ]:
# compute the variance along the row
print(np.var(arr, axis=0))

[0.02280245 0.07256599 0.03334464 0.0400337  0.11227883]


In [ ]:
# compute the variance along the column
print(np.var(arr, axis=1))

[0.11558401 0.04734919 0.08844089 0.04019649 0.01771775]


### compute the covariance

In [6]:
arr = np.random.rand(5,8)
print(arr)

[[0.35020733 0.67212088 0.1633815  0.92270107 0.15041202 0.26328053
  0.39573116 0.98646965]
 [0.38188354 0.06661727 0.29867663 0.7554213  0.98038536 0.77825774
  0.77024922 0.56431351]
 [0.21109549 0.71508305 0.58968645 0.4593863  0.80775907 0.63519274
  0.1972452  0.88811884]
 [0.96502352 0.89769068 0.5659693  0.08154506 0.03000792 0.88861738
  0.04375782 0.49469529]
 [0.67558682 0.65676454 0.29587618 0.3471824  0.38196737 0.79496374
  0.84251309 0.57034766]]


In [ ]:
print(np.cov(arr))

[[ 0.05402285  0.03916784  0.03506723  0.0367739  -0.02741259]
 [ 0.03916784  0.03992086  0.01853696  0.04299328 -0.02678781]
 [ 0.03506723  0.01853696  0.06217596  0.01094847  0.00254219]
 [ 0.0367739   0.04299328  0.01094847  0.11372942 -0.02614117]
 [-0.02741259 -0.02678781  0.00254219 -0.02614117  0.06564368]]


### element-wise comparison

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,3,2,1])

In [ ]:
# return an array of bools
print(arr1 == arr2)    
print(arr1 < 3)

[False False  True False False]
[ True  True False False False]


# Slicing & Indexing

In [ ]:
arr = np.array(range(100)).reshape((10,10))

### select an element by row and column indices

In [ ]:
print(arr[5][5])
# or more concisely
print(arr[5,5])

55
55


### indexing with slicing

In [ ]:
print(arr[1:3, 4:6])

[[14 15]
 [24 25]]


### boolean indexing

In [ ]:
arr1 = np.arange(25).reshape((5,5))
bools = np.array([True, True, False, True, False])
print(arr1[bools])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [15 16 17 18 19]]


In [ ]:
# negate the condition
print(arr1[~bools])    

[[10 11 12 13 14]
 [20 21 22 23 24]]


### fancy indexing

In [8]:
arr = np.random.rand(10,10)
print(arr)

[[0.85856668 0.33936053 0.21604264 0.92065534 0.79713853 0.8972448
  0.61041921 0.38472888 0.24396331 0.35899878]
 [0.52680135 0.96961856 0.47417689 0.93752102 0.47863105 0.64271569
  0.42971434 0.83691376 0.72192833 0.61417802]
 [0.62036105 0.2552051  0.67732422 0.99716217 0.36822796 0.51696763
  0.11089545 0.27017664 0.34310224 0.94480775]
 [0.81775992 0.25044391 0.05768638 0.93666641 0.96116312 0.5262541
  0.71178448 0.46757754 0.30951138 0.4080766 ]
 [0.25940897 0.02561471 0.87680731 0.51196696 0.45822888 0.68662326
  0.19041395 0.6042182  0.72907629 0.59985811]
 [0.28443432 0.80302442 0.934066   0.40561848 0.38306818 0.79829453
  0.3282947  0.98458845 0.36518568 0.55349632]
 [0.77934969 0.34421547 0.52364781 0.29825765 0.98876311 0.34947301
  0.69047429 0.31599962 0.26337686 0.32379041]
 [0.40577264 0.79403756 0.74923862 0.14530855 0.72917658 0.78412442
  0.5249948  0.31277287 0.17149373 0.61277059]
 [0.00668176 0.56387637 0.13364277 0.74985094 0.34281586 0.63415462
  0.77074962 0

In [9]:
# select rows 3,1,2 with columns 6,4,8 
print(arr[[3,1,2]][:, [6,4,8]])    

[[0.71178448 0.96116312 0.30951138]
 [0.42971434 0.47863105 0.72192833]
 [0.11089545 0.36822796 0.34310224]]


### find elements/indices by conditions

In [10]:
arr = np.arange(16).reshape(4,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [11]:
# find the elements greater than 5 and return a flattened array
print(arr[arr>5])    # or arr[np.where(arr>5)]

[ 6  7  8  9 10 11 12 13 14 15]


In [12]:
# return values based on conditions 
# np.where(condition, true_return, false_return)
print(np.where(arr>5, "True", "False"))

[['False' 'False' 'False' 'False']
 ['False' 'False' 'True' 'True']
 ['True' 'True' 'True' 'True']
 ['True' 'True' 'True' 'True']]


In [ ]:
# find the indices of the elements on conditions
print(np.argwhere(arr>5))

[[1 2]
 [1 3]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [3 0]
 [3 1]
 [3 2]
 [3 3]]


# Sort an Array

In [ ]:
arr = np.random.rand(5,5)

### sort an array along a specified axis

In [ ]:
# sort along the row and return a copy
print(np.sort(arr, axis=0))   

[[0.11702945 0.17913374 0.06753657 0.02945699 0.05396756]
 [0.13630925 0.18249983 0.41165849 0.12910116 0.31981183]
 [0.36056504 0.51866089 0.42053876 0.56232065 0.37163583]
 [0.44498496 0.62847058 0.42945962 0.70682921 0.43148605]
 [0.7740198  0.74238635 0.55147061 0.86890785 0.75572196]]


In [ ]:
# sort along the row in place
arr.sort(axis=0)
print(arr)

[[0.11702945 0.17913374 0.06753657 0.02945699 0.05396756]
 [0.13630925 0.18249983 0.41165849 0.12910116 0.31981183]
 [0.36056504 0.51866089 0.42053876 0.56232065 0.37163583]
 [0.44498496 0.62847058 0.42945962 0.70682921 0.43148605]
 [0.7740198  0.74238635 0.55147061 0.86890785 0.75572196]]


In [ ]:
# sort along the column and return a copy
print(np.sort(arr, axis=1))    

[[0.02945699 0.05396756 0.06753657 0.11702945 0.17913374]
 [0.12910116 0.13630925 0.18249983 0.31981183 0.41165849]
 [0.36056504 0.37163583 0.42053876 0.51866089 0.56232065]
 [0.42945962 0.43148605 0.44498496 0.62847058 0.70682921]
 [0.55147061 0.74238635 0.75572196 0.7740198  0.86890785]]


In [ ]:
# sort along the column in place
arr.sort(axis=1)    
print(arr)

[[0.02945699 0.05396756 0.06753657 0.11702945 0.17913374]
 [0.12910116 0.13630925 0.18249983 0.31981183 0.41165849]
 [0.36056504 0.37163583 0.42053876 0.51866089 0.56232065]
 [0.42945962 0.43148605 0.44498496 0.62847058 0.70682921]
 [0.55147061 0.74238635 0.75572196 0.7740198  0.86890785]]


# Manipulate an Array

### transpose an array

In [14]:
# the following methods return a copy
print(arr.T)
# or 
print(np.transpose(arr))
# or
print(arr.transpose())

[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]
[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]
[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


### change the shape of an array

In [ ]:
# change the shape of an array and return a copy
arr.reshape((2,6))

array([[0.80614361, 0.86728799, 0.08910079, 0.67553447, 0.61240133,
        0.65205696],
       [0.05760322, 0.38582245, 0.73322903, 0.13585084, 0.56708195,
        0.02315444]])

In [ ]:
# change the shape of an array in place
arr.resize((2,6))

### flatten an array

In [ ]:
# return a copy
arr.flatten()    

array([0.80614361, 0.86728799, 0.08910079, 0.67553447, 0.61240133,
       0.65205696, 0.05760322, 0.38582245, 0.73322903, 0.13585084,
       0.56708195, 0.02315444])

### append elements to an array

In [ ]:
arr = np.array([1,2,3])

In [ ]:
# append a scalar and return a copy
arr1 = np.append(arr, 4)    
print(arr1)

[1 2 3 4]


In [ ]:
# append an array and return a copy
arr2 = np.append(arr, [4,5,6])    
print(arr2)

[1 2 3 4 5 6]


### insert elements into an array

In [ ]:
# np.insert(array, position, element)

# insert a scalar at a certain position
arr3 = np.insert(arr, 0, 100)    
print(arr3)

[100   1   2   3]


In [ ]:
# insert multiple values at a certain position
arr3 = np.insert(arr, 0, [1,2,3])    
print(arr3)

[1 2 3 1 2 3]


### delete elements from an array

In [ ]:
# remove the element at position 0
arr4 = np.delete(arr, 0)    
print(arr4)

[2 3]


In [ ]:
# remove the element at multiple positions
arr4 = np.delete(arr, [0,2])    
print(arr4)

[2]


### copy an array

In [ ]:
arr = np.array([1,2,3])

In [ ]:
# the following methods are all deep copy
arr1 = np.copy(arr)
# or 
arr1 = arr.copy()
# or 
arr1 = np.array(arr, copy=True)

# Combine & Split an Array

In [ ]:
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])

### ```np.concatenate((a, b), axis=0)```

In [ ]:
# concat along the row
cat = np.concatenate((arr1, arr2), axis=0)        
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [ ]:
# concat along the column
cat = np.concatenate((arr1, arr2), axis=1)    
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### ```np.vstack((a, b))``` 

In [ ]:
# stack arrays vertically
cat = np.vstack((arr1, arr2))
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


### ```np.hstack((a, b))```


In [ ]:
# stack arrays horizontally
cat = np.hstack((arr1, arr2))
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


# Set Operations

### select the unique elements from an array

In [ ]:
arr = np.array([1,1,2,2,3,3,4,5,6])
print(np.unique(arr))

[1 2 3 4 5 6]


In [ ]:
# return the number of times each unique item appears
arr = np.array([1,1,2,2,3,3,4,5,6])
uniques, counts = np.unique(arr, return_counts=True)
print(uniques)
print(counts)

[1 2 3 4 5 6]
[2 2 2 1 1 1]


### compute the intersection & union of two arrays

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])

In [ ]:
# intersection
print(np.intersect1d(arr1, arr2))

[3 4 5]


In [ ]:
# union
print(np.union1d(arr1, arr2))

[1 2 3 4 5 6 7]


### compute the elements in an array that are not in another

In [ ]:
print(np.setdiff1d(arr1, arr2))

[1 2]


### compute the elements in either of two arrays, but not both

In [ ]:
print(np.setxor1d(arr1, arr2))

[1 2 6 7]


# Linear Algebra

In [15]:
arr1 = np.random.rand(5,5)
arr2 = np.random.rand(5,5)

### matrix multiplication

In [16]:
print(arr1.dot(arr2))
# or
print(np.dot(arr1, arr2))
# or
print(arr1 @ arr2)

[[0.55027213 1.06243867 1.48957422 1.12684463 0.93017488]
 [0.97198446 2.39213984 3.06001449 2.05410597 2.23604282]
 [0.40063697 1.0543184  1.27279687 0.78994808 0.80955434]
 [0.78566131 1.91238438 2.60456087 1.82549035 2.25012749]
 [0.44596591 1.01386458 1.44314311 1.04142107 1.33091321]]
[[0.55027213 1.06243867 1.48957422 1.12684463 0.93017488]
 [0.97198446 2.39213984 3.06001449 2.05410597 2.23604282]
 [0.40063697 1.0543184  1.27279687 0.78994808 0.80955434]
 [0.78566131 1.91238438 2.60456087 1.82549035 2.25012749]
 [0.44596591 1.01386458 1.44314311 1.04142107 1.33091321]]
[[0.55027213 1.06243867 1.48957422 1.12684463 0.93017488]
 [0.97198446 2.39213984 3.06001449 2.05410597 2.23604282]
 [0.40063697 1.0543184  1.27279687 0.78994808 0.80955434]
 [0.78566131 1.91238438 2.60456087 1.82549035 2.25012749]
 [0.44596591 1.01386458 1.44314311 1.04142107 1.33091321]]


### compute eigen values

In [ ]:
arr = np.random.rand(5,5)
print(np.linalg.eigvals(arr))

### eigen value decomposition

In [ ]:
arr = np.random.rand(5,5)

w, v = np.linalg.eig(arr)
print(w)    # eigen values
print(v)    # eigen vectors

### compute the trace & determinant

In [ ]:
# notice this is not a function in linalg!!!
print(np.trace(arr))

In [ ]:
print(np.linalg.det(arr))

In [ ]:
# compute the inverse of a matrix
arr = np.random.rand(5,5)
print(np.linalg.inv(arr))